name: Node.js

on:
  schedule:
    - cron: '0 6 * * 1-5'

jobs:
  run:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Run
        run: npm start
        env:
          MICROSOFT_EMAIL: ${{ secrets.MICROSOFT_EMAIL }}
          MICROSOFT_PASSWORD: ${{ secrets.MICROSOFT_PASSWORD }}
